#!/bin/bash
TOKEN=$(./token)
curl -X POST \
  'https://dev-yasm.prodyna.com/api/graph/v1/languages/search' \
  -H 'accept: application/json' \
  -H "Authorization: Bearer $TOKEN" \
  -H 'Content-Type: application/json' \
  -d '{
  "term": "",
  "skip": 0,
  "limit": 20
}'
