name: Push or daily trigger

on:
  workflow_dispatch:
  schedule:
    - cron: '30 7 * * *'
  push:
    branches:
      - main

jobs:

  call-overview:
    uses: "prodyna-yasm/.github/.github/workflows/overview.yaml@main"
    secrets:
      token: ${{ secrets.OVERVIEW_TOKEN }}
