name: "Invite: Trigger"

on:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/'

jobs:

  call-overview:
    uses: "prodyna-yasm/.github/.github/workflows/invite.yaml@main"
    secrets:
      token: ${{ secrets.OVERVIEW_TOKEN }}
