name: "Invite"

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  invite-to-org:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Invite to organization
        uses: prodyna/invite-to-org@v1.1
        with:
          # The GitHub Token to use for authentication, it needs permissions to read member in source-org and invite them to the target-org
          github-token: ${{ inputs.token }}
          enterprise: "prodyna"
          source-organization: "prodyna"
          target-organization: "prodyna-yasm"
          dry-run: false
          verbose: 3
          team: yasm-all
