name: "Invite: Trigger"
permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/'

jobs:

  call-invite:
    uses: "prodyna-yasm/.github/.github/workflows/invite.yaml@main"
    secrets:
      token: ${{ secrets.INVITE_TOKEN }}
