name: "Invite"

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  invite-to-org:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Invite to organization
        uses: prodyna/invite-to-org@v1.0
