name: Create Overview

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  create-overview:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token }}
          repository: prodyna-yasm/.github

      # Create directory profile if it does not exist
      - name: Create profile directory
        run: mkdir -p profile

      - name: Deployment overview
        uses: prodyna/deployment-overview@v0.7
        with:
          organization: prodyna-yasm
          repositories: yasm-backend,yasm-frontend,yasmctl,yasm-proxy-odbc,yasm-integration,yasm-geocoding,yasm-data,yasm-gotenberg,yasm-infrastructure-staged,yasm-api
          environments: dev,staging,prod
          environment-links: https://dev-yasm.prodyna.com,https://staging-yasm.prodyna.com,https://yasm.prodyna.com
          verbose: 1
          github-token: ${{ secrets.token }}
          title: "YASM Deployment Overview"
          target-json-file: profile/deployment-overview.json
          target-md-file: profile/README.md

      - name: Commit changes
        run: |
          git config --local user.email "darko@krizic.net"
          git config --local user.name "Deployment Overview"
          git add profile
          git commit -m "Add/update deployment overview"
          git push
